name: pendant_minimal
description: Limitless Pendant BLE audio receiver and uploader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.13
  path_provider: ^2.1.2
  http: ^1.2.1
  permission_handler: ^11.3.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
